# Fill in your AWS Access Key ID and Secret Access Key
# http://aws.amazon.com/security-credentials
local:
    notifications_domain: in.localhost.notifications
    notifications_queues_domain: in.localhost.notifications.queues
    access_key_id: AKIAIERRYQXDX7KCTHPQ
    secret_access_key: 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
    mounted_s3_certificate_bucket: /mnt/s3/local_brightpush_ios_certificates_pem/

development:
    notifications_domain: in.brightpushalpha.notifications
    notifications_queues_domain: in.brightpushalpha.notifications.queues
    access_key_id: AKIAIERRYQXDX7KCTHPQ
    secret_access_key: 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
    mounted_s3_certificate_bucket: /mnt/s3/alpha_brightpush_ios_certificates_pem/

test:
    notifications_domain: in.brightpushbeta.notifications
    notifications_queues_domain: in.brightpushbeta.notifications
    access_key_id: AKIAIERRYQXDX7KCTHPQ
    secret_access_key: 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
    mounted_s3_certificate_bucket: /mnt/s3/beta_brightpush_ios_certificates_pem/
    
production:
    notifications_domain: in.brightpush.notifications
    notifications_queues_domain: in.brightpush.notifications
    access_key_id: AKIAIERRYQXDX7KCTHPQ
    secret_access_key: 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
    mounted_s3_certificate_bucket: /mnt/s3/brightpush_ios_certificates_pem/